spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #activation eureka locator
          lowerCaseServiceId: true
      # Configuration des routes de l'API Gateway
      routes:
        #Service UTILISATEUR
        - id: UTILISATEUR
          uri: lb://UTILISATEUR/ #Attention : lb et pas HTTP. Lb est prêt pour faire du load-balancing
          predicates:
            - Path=/api/user/**
        #Service ACCESSCARD
        - id: ACCESSCARD
          uri: lb://ACCESSCARD/
          predicates:
            - Path=/api/accessCard/**
        #Service COMPOSITE-USERACCESSCARD
        - id: COMPOSITE-USERACCESSCARD
          uri: lb://COMPOSITE-USERACCESSCARD/
          predicates:
            - Path=/api/userAccess/**
        #Service station
        - id: STATION
          uri: lb://STATION/
          predicates:
            - Path=/api/station/**
        #Service car
        - id: CAR
          uri: lb://CAR/
          predicates:
            - Path=/api/car/**
        #Service Location
        - id: LOCATION
          uri: lb://LOCATION/
          predicates:
            - Path=/api/location/**
      enabled: on # Activation gateway
    # Activation remontée management dans Eureka
    config:
      service-registry:
        auto-registration:
          register-management: on
logging:
  level:
    org.springframework.web: DEBUG
